### ISSUE TITLE
Add email confirmation step after survey

### ISSUE THREAD

**Issue by asciimo** [sfvtech/pay-per-view#15]
One request from FARM is to give viewers a chance to correct their originally submitted email addresses after the survey. This is because some people enter nonsense email values initially, but change their minds after watching the video.

After the viewer has completed the survey, display an email confirmation screen:

        Is this your correct email address?
                 user@email.com
                [no]      [yes]
If the user taps "yes," proceed to the "thank you screen"
If the user taps "no," display an email form with the field prepopulated with its original (incorrect) value.

**Comment by ekager** [comment]
Yes I thought this made sense! I added an EditViewerFragment after the video where users have a chance to edit their entry and change their name + email address, and also to remove/add viewers. Would we want this as well after that screen?

**Comment by asciimo** [comment]
I think the EditViewerFragment should come after each viewer's survey. Admins should be able to add or remove viewers right up until the video starts. After that they should only be able to remove viewers. (Someone coming in halfway through the video doesn't count as a full viewer.) I think this should be done through the admin menu, which will have to be aware of the current session state, if any.
