### ISSUE TITLE
Add / Remove viewers

### ISSUE THREAD

**Issue by asciimo** [sfvtech/pay-per-view#2]
Add capability to add and remove viewers after the "how many viewers are there?" selection has been made. (MAX_VIEWERS should be configurable, but let's assume it's 3 for now until configuration is fleshed out.) Specifically:

1. Ability to add up to MAX_VIEWERS before the video starts
1. Ability to remove one or more viewers at any time

Some thoughts about the UX
- When a new viewer is added, they should be prompted for their first name and email address. 
- Removing the last viewer should clear out the session and return to the first screen

**Comment by asciimo** [comment]
The UX for this is confusing. For example:
1. tap 1
2. enter name 
3. enter e-mail but don't tap OK
4. open admin menu
5. Note that there is no "add viewer" option
6. tap "cancel" and the session restarts

**Comment by asciimo** [comment]
UX is much better with [2] and [3] buttons. 

There seem to be some issues with viewer state when entering the admin menu and increasing the viewer count.

- When the admin menu is opened during onboarding and [cancel] is tapped, the current viewer form gets reset. I would expect the form to be restored to its state prior to opening the admin menu.
- When number of viewers is increased from 2->3, viewer onboarding starts at a blank "Viewer 1" form. The [next] button proceeds to the "Viewer 3" form.
- While filling out the Viewer 3 form, if you open the admin menu, there is no option to change the number of viewers. 

What are your thoughts on reducing the number of viewers?  This requires reducing the number of viewers by deleting one or more. Perhaps show the Verify Viewers view, with the heading "Select Viewers to Remove?" The Admin could then delete any number of viewers. 

Update: I just returned to onboarding to test orientation change behavior (#21). After the view returned to Viewer 1, I filled out the form and tapped "next." The heading on the subsequent form was Viewer 7. There seems to be a good state bug in here somewhere :)

**Comment by ekager** [comment]
I fixed the first two issues and the update issue in my latest PR. 

So my thoughts are that it really only makes sense to "add" viewers during ViewerInfo fragment after the initial number selection and before the video starts. There is a max viewer limit of 3 so it's not really "adding" viewers as much as increasing the max viewer size? This is also why when you're on the 3rd viewer form, you can't "add" more viewers in the menu. It's already at the max. 

After this point the video starts and I'm assuming the admins won't want to interrupt the video to add/edit/remove viewers. 

After the video finishes, it makes sense to remove or edit viewers so only in the SurveyFragment I have enabled this. 

What do you think?
