### ISSUE TITLE
Update theme

### ISSUE THREAD

**Issue by asciimo** [sfvtech/pay-per-view#4]
The styles in the app are probably not implemented using best practices, and will probably break on a variety of devices.  Please update the layouts to enforce sanity.

Attached is an image of the design of the truck. The theme styles should be configurable to match. I will see if I can get font names and color codes so that we can tweak that configuration later.  Not sure if we should have fruit animations...?

![10bl_sprintervandesign](https://user-images.githubusercontent.com/70218/30796377-9a61a4da-a186-11e7-8f80-0414b8e14a91.jpg)

**Comment by ekager** [comment]
If we could get the image files for some of these, I may be able to incorporate them into the app in some empty space!

**Comment by asciimo** [comment]
It looks like they have totally rebranded again, so I'm closing this.
