### ISSUE TITLE
Add support for downloading and setting new target video 

### ISSUE THREAD

**Issue by ekager** [sfvtech/pay-per-view#9]

**Comment by asciimo** [comment]
I built this (0025e5a1) and attempted to download a video from my desktop. The device seemed to have kicked off a download, but it stuck at 0% (paused), and I never saw the request to my desktop Web server.

**Comment by ekager** [comment]
How did you download from your desktop? It has to be a web URI to work. Was it an mp4 file?

**Comment by asciimo** [comment]
This is broken and I have made a branch (testing-for-tour) to hack around it.

1. Entering a URL to download a video works, kicking off a system download process. However, when the video download is complete, the app does not catch the event from the OS and therefore does not update the shared preference with the path to the video
2. When attempting to set Local URI for Video, Local URI for Subtitles is instead updated on the main admin view.

**Comment by ekager** [comment]
#26 should fix these issues. For 2, videos have to be .mp4 and subtitles have to be .srt. I changed it so it wouldn't default to subtitles though. I can throw a toast up as well for feedback if the download goes wrong.

**Comment by asciimo** [comment]
Yeah, the file was definitely .mp4. Is it possible the dot should be
excluded?

**Comment by ekager** [comment]
Exactly. See #26
